const menu = {
    "starters": [
        {"id": "1", "name": "Special Appetiser" ,"price": 7.30},
        {"id": "2", "name": "Sesame Prawn on Toast" ,"price": 3.50},
        {"id": "3", "name": "Seaweed" ,"price": 3.40},
        {"id": "4", "name": "Pancake Rolls" ,"price": 1.60},
        {"id": "5", "name": "Prawn Cocktail " ,"price": 3.20},
        {"id": "6", "name": "Mini Vegetarian Pancake Rolls (10)" ,"price": 3.40},
        {"id": "7", "name": "Sweet & Sour Prawn Balls (10)" ,"price": 4.80},
        {"id": "8", "name": "Sweet & Sour Chicken Balls (10)" ,"price": 4.40},
        {"id": "9", "name": "Sweet & Sour Pork Balls (10)" ,"price": 3.70},
        {"id": "10", "name": "Chicken in Breadcrumbs" ,"price": 4.70},
        {"id": "11", "name": "King Prawns in Breadcrumbs" ,"price": 4.70},
        {"id": "12", "name": "Chicken Satay on Skewers (4) " ,"price": 4.30},
        {"id": "13", "name": "Satay Sauce" ,"price": 1.40},
        {"id": "14", "name": "Sweet & Sour Sauce" ,"price": 1.40},
        {"id": "15", "name": "Curry Sauce" ,"price": 1.20},
        {"id": "16", "name": "Barbecue Sauce" ,"price": 1.20},
        {"id": "17", "name": "Chips" ,"price": 1.40},
        {"id": "18", "name": "Prawn Crackers" ,"price": 1.30},
        {"id": "19", "name": "Banana Fritters in Syrup" ,"price": 2.20},
        {"id": "20", "name": "Pineapple Fritters in Syrup" ,"price": 2.20},
        {"id": "21", "name": "Hot & Sour Soup" ,"price": 2.30},
        {"id": "22", "name": "Chicken & Sweetcorn Soup" ,"price": 2.3},
        {"id": "23", "name": "Crab Meat & Sweetcorn Soup" ,"price": 2.30},
        {"id": "24", "name": "Chicken & Mushroom Soup" ,"price": 2.00},
        {"id": "25", "name": "Chicken & Noodle Soup" ,"price": 2.00},
        {"id": "26", "name": "Seafood & Sweetcorn Soup" ,"price": 2.60},
        {"id": "27", "name": "Sweetcorn Soup" ,"price": 2.00},
        {"id": "27a", "name": "Won Ton Soup" ,"price": 3.00},
    ],
    "rice": [
        {"id": "28", "name": "House Special Rice", "price": 4.50},
        {"id": "29", "name": "Special Fried Rice", "price": 3.80},
        {"id": "30", "name": "Chicken Fried Rice", "price": 3.80},
        {"id": "31", "name": "King Prawn Fried Rice", "price": 4.60},
        {"id": "32", "name": "Shrimp Fried Rice", "price": 3.80},
        {"id": "33", "name": "Roast Pork Fried Rice", "price": 3.80},
        {"id": "34", "name": "Beef Fried Rice", "price": 3.80},
        {"id": "35", "name": "Roast Duck Fried Rice", "price": 4.40},
        {"id": "36", "name": "Mushroom Fried Rice", "price": 3.40},
        {"id": "37", "name": "Vegetable Fried Rice", "price": 3.40},
        {"id": "38", "name": "Egg Fried Rice (medium)", "price": 2.60},
        {"id": "39", "name": "Boiled Rice (medium)", "price": 2.20},
        {"id": "40", "name": "Singapore Fried Rice", "price": 4.20},
        {"id": "41", "name": "Vegetarian Singapore Fried Rice", "price": 3.60},
        {"id": "42", "name": "Roast Duck with Boiled Rice", "price": 5.00},
        {"id": "43", "name": "Seafood Fried Rice ", "price": 5.00},
        {"id": "44", "name": "Chicken in Black Bean Sauce with Boiled Rice ", "price": 4.60},
        {"id": "45", "name": "Beef in Black Bean Sauce with Boiled Rice", "price": 4.60},
        {"id": "46", "name": "Mixed Meat in Black Bean Sauce with Boiled Rice ", "price": 4.60},
        {"id": "47", "name": "Quarter Chicken with Boiled Rice", "price": 4.00},
    ],
    "noodles": [
        {"id": "48", "name": "House Special Chow Mein", "price": 4.50},
        {"id": "49", "name": "Special Chow Mein", "price": 4.00},
        {"id": "50", "name": "Chicken Chow Mein", "price": 3.80},
        {"id": "51", "name": "King Prawn Chow Mein", "price": 4.60},
        {"id": "52", "name": "Shrimp Chow Mein", "price": 4.00},
        {"id": "53", "name": "Roast Pork Chow Mein", "price": 4.00},
        {"id": "54", "name": "Beef Chow Mein", "price": 3.90},
        {"id": "55", "name": "Roast Duck Chow Mein", "price": 4.50},
        {"id": "56", "name": "Quarter Chicken with Chow Mein", "price": 4.30},
        {"id": "57", "name": "Sirloin Steak with Chow Mein", "price": 5.90},
        {"id": "58", "name": "Mushroom Chow Mein", "price": 3.40},
        {"id": "59", "name": "Vegetable Chow Mein", "price": 3.60},
        {"id": "60", "name": "Plain Chow Mein (medium)", "price": 2.80},
        {"id": "61", "name": "Singapore Chow Mein", "price": 4.20},
        {"id": "62", "name": "Vegetarian Singapore Chow Mein", "price": 4.20},
        {"id": "63", "name": "Singapore Rice Noodles", "price": 4.60},
        {"id": "64", "name": "Vegetarian Singapore Rice Noodles", "price": 4.20},
        {"id": "65", "name": "Seafood Chow Mein", "price": 5.50},
        {"id": "66", "name": "Seafood Rice Noodles", "price": 5.50},
        {"id": "67", "name": "Chicken in Black Bean Sauce with Chow Mein", "price": 4.60},
        {"id": "68", "name": "Beef in Black Bean Sauce with Chow Mein", "price": 4.60},
        {"id": "69", "name": "Mixed Meat in Black Bean Sauce with Chow Mein ", "price": 4.60},
        {"id": "70", "name": "Roast Duck with Noodles", "price": 4.50},
    ],
    "chicken": [
        {"id": "71", "name": "Chicken with Cashew Nuts", "price": 4.40},
        {"id": "72", "name": "Chicken with Green Pepper in Black Bean Sauce ", "price": 4.40},
        {"id": "73", "name": "Chicken with Ginger & Spring Onions", "price": 4.40},
        {"id": "74", "name": "Smoked Chicken ", "price": 4.60},
        {"id": "75", "name": "Chicken with Straw Mushrooms", "price": 4.40},
        {"id": "76", "name": "Sweet & Sour Chicken Hong Kong Style", "price": 4.30},
        {"id": "77", "name": "Lemon Chicken", "price": 4.30},
        {"id": "78", "name": "Shredded Chicken in Salt & Chilli", "price": 4.30},
        {"id": "79", "name": "Chicken Wings in Salt & Chilli ", "price": 4.30},
        {"id": "80", "name": "Chicken in Chilli Sauce", "price": 4.30},
        {"id": "81", "name": "Chicken with Cashew Nuts in Yellow Bean Sauce", "price": 4.30},
        {"id": "82", "name": "Chicken with Mushrooms", "price": 4.30},
        {"id": "83", "name": "Chicken with Tomatoes", "price": 4.30},
        {"id": "84", "name": "Chicken with Pineapple", "price": 4.30},
        {"id": "85", "name": "Chicken in Garlic Sauce", "price": 4.30},
        {"id": "86", "name": "Chicken with Mixed Vegetables", "price": 4.30},
        {"id": "87", "name": "Chicken Szechuan Style (hot & spicy)", "price": 4.30},
        {"id": "88", "name": "Kung Po Chicken", "price": 4.30},
        {"id": "89", "name": "Chicken in Oyster Sauce", "price": 4.30},
        {"id": "90", "name": "Chicken with Chinese Mushrooms & Bamboo Shoots", "price": 4.30},
        {"id": "91", "name": "Sha Sha Chicken", "price": 4.30},
        {"id": "92", "name": "Chicken Chinese Style", "price": 4.30},
        {"id": "93", "name": "Grilled Chicken Peking Style in Garlic Sauce", "price": 4.50},
        {"id": "94", "name": "Shredded Chilli Chicken", "price": 4.50},
        {"id": "94a", "name": "Quarter Chicken with Chips", "price": 4.60},
    ],
    "beef": [
        {"id": "95", "name": "Beef with Green Pepper in Black Bean Sauce", "price": 4.30},
        {"id": "95a", "name": "Kung Po Beef", "price": 4.30},
        {"id": "96", "name": "Beef with Ginger & Spring Onion", "price": 4.30},
        {"id": "97", "name": "Beef with Cashew Nuts", "price": 4.30},
        {"id": "98", "name": "Beef with Straw Mushrooms", "price": 4.30},
        {"id": "99", "name": "Beef in Chilli Sauce", "price": 4.30},
        {"id": "100", "name": "Beef in Oyster Sauce", "price": 4.30},
        {"id": "101", "name": "Beef with Mushrooms", "price": 4.30},
        {"id": "102", "name": "Beef with Chinese Mushrooms & Bamboo Shoots", "price": 4.30},
        {"id": "103", "name": "Beef with Mixed Vegetables", "price": 4.30},
        {"id": "104", "name": "Beef in Garlic Sauce", "price": 4.30},
        {"id": "105", "name": "Beef with Tomatoes", "price": 4.30},
        {"id": "106", "name": "Beef with Cashew Nuts in Yellow Bean Sauce", "price": 4.30},
        {"id": "107", "name": "Fried Crispy Chilli Beef", "price": 4.30},
        {"id": "108", "name": "Beef Szechuan Style (hot & spicy) ", "price": 4.30},
        {"id": "109", "name": "Sirloin Steak with Chips & Peas", "price": 6.20},
        {"id": "110", "name": "Beef with Onions", "price": 4.30},
    ],
    "seafood": [
        {"id": "111", "name": "King Prawns with Ginger & Spring Onion", "price": 4.80},
        {"id": "112", "name": "King Prawns with Green Pepper in Black Bean Sauce", "price": 4.80},
        {"id": "113", "name": "King Prawns Szechuan Style (hot & spicy)", "price": 4.80},
        {"id": "114", "name": "King Prawn Satay", "price": 4.80},
        {"id": "115", "name": "King Prawns with Cashew Nuts", "price": 4.80},
        {"id": "116", "name": "King Prawns in Oyster Sauce", "price": 4.80},
        {"id": "117", "name": "King Prawns in Chilli Sauce", "price": 4.80},
        {"id": "118", "name": "King Prawns with Pineapple", "price": 4.80},
        {"id": "119", "name": "King Prawns with Mushrooms", "price": 4.80},
        {"id": "120", "name": "King Prawns in Garlic Sauce", "price": 4.80},
        {"id": "121", "name": "Sweet & Sour King Prawns Hong Kong Style", "price": 4.80},
        {"id": "122", "name": "King Prawns with Cashew Nuts in Yellow Bean Sauce ", "price": 4.80},
        {"id": "123", "name": "Kung Po King Prawns", "price": 4.80},
        {"id": "124", "name": "King Prawns in Salt & Chilli", "price": 4.80},
        {"id": "125", "name": "King Prawns with Tomatoes", "price": 4.80},
        {"id": "126", "name": "King Prawns with Chinese Mushrooms & Bamboo Shoots", "price": 4.80},
        {"id": "127", "name": "King Prawns with Mixed Vegetables", "price": 4.80},
        {"id": "128", "name": "King Prawns with Straw Mushrooms", "price": 4.80},
        {"id": "129", "name": "Squid in Salt & Chilli", "price": 4.70},
        {"id": "130", "name": "Squid with Green Pepper in Black Bean Sauce ", "price": 4.70},
        {"id": "131", "name": "Squid with Ginger & Spring Onion", "price": 5.30},
        {"id": "132", "name": "Mussels with Ginger & Spring Onion", "price": 5.30},
        {"id": "133", "name": "Mussels with Green Pepper in Black Bean Sauce", "price": 4.70},
        {"id": "134", "name": "Mussels in Garlic Sauce", "price": 4.70},
        {"id": "135", "name": "Grilled Dumplings", "price": 3.70},
        {"id": "136", "name": "Mini Duck Rolls", "price": 3.70},
        {"id": "137", "name": "Crab Meat with. Straw Mushrooms", "price": 4.80},
    ],
    "duck": [
        {"id": "138", "name": "Crispy Aromatic Duck (served with pancakes, spring onion, cucumber & hoi sin sauce) Quarter", "price": 7.20 },
        {"id": "138Q", "name": "Crispy Aromatic Duck (served with pancakes, spring onion, cucumber & hoi sin sauce) Quarter", "price": 12.80 },
        {"id": "138W", "name": "Crispy Aromatic Duck (served with pancakes, spring onion, cucumber & hoi sin sauce) Quarter", "price": 25.00 },
        {"id": "139", "name": "Roast Duck Chinese Style", "price": 4.70},
        {"id": "140", "name": "Duck with Ginger & Spring Onion", "price": 4.70},
        {"id": "141", "name": "Roast Duck Peking Style", "price": 4.70},
        {"id": "142", "name": "Roast Duck with Green Pepper in Black Bean Sauce ", "price": 4.70},
        {"id": "143", "name": "Roast Duck in Lemon Sauce", "price": 4.80},
        {"id": "144", "name": "Roast Duck with Mushrooms", "price": 4.70},
        {"id": "145", "name": "Roast Duck in Plum Sauce", "price": 4.70},
        {"id": "146", "name": "Roast Duck with Pineapple", "price": 4.70},

    ],
    "pork": [
        {"id": "147", "name": "Sweet & Sour Pork Hong Kong Style", "price": 3.80},
        {"id": "148", "name": "Roast Pork Chinese Style", "price": 4.30},
        {"id": "149", "name": "Roast Pork with Green Pepper in Black Bean Sauce", "price": 4.30},
        {"id": "150", "name": "Crispy Pork with Green Pepper in Black Bean Sauce ", "price": 4.40},
        {"id": "151", "name": "Roast Pork with Mushrooms", "price": 4.40},
        {"id": "152", "name": "Chinese Crispy Pork (hoi sin sauce)", "price": 5.00},
        {"id": "153", "name": "Spare Ribs (dry)", "price": 4.80},
        {"id": "154", "name": "Spare Ribs in Barbecue Sauce", "price": 4.80},
        {"id": "155", "name": "Capital Spare Ribs", "price": 4.80},
        {"id": "156", "name": "Honey Barbecue Spare Ribs", "price": 4.80},
        {"id": "157", "name": "Spare Ribs in Salt & Chilli ", "price": 4.80},
        {"id": "158", "name": "Sweet & Sour Spare Ribs", "price": 4.80},
        {"id": "159", "name": "Spare Ribs with Green Pepper in Black Bean Sauce ", "price": 4.80},
        {"id": "160", "name": "Spare Ribs in Satay Sauce", "price": 4.80},
        {"id": "161", "name": "Spare Ribs in Chili Sauce", "price": 4.80},
    ],
    "vegetable": [
        {"id": "171", "name": "Vegetable Curry", "price": 3.30},
        {"id": "172", "name": "Stewed Mixed Vegetables", "price": 3.30},
        {"id": "173", "name": "Stewed Bean Sprouts", "price": 3.30},
        {"id": "174", "name": "Stewed Mushrooms", "price": 3.30},
        {"id": "175", "name": "Braised Straw Mushrooms", "price": 3.70},
        {"id": "176", "name": "Mushrooms in Salt & Chilli", "price": 3.80},
        {"id": "177", "name": "Sweet & Sour Vegetables", "price": 3.30},
        {"id": "178", "name": "Stewed Bamboo Shoots & Water Chestnuts", "price": 3.30},
    ],
    "curry": [
        {"id": "162", "name": "House Special Curry", "price": 4.20},
        {"id": "163", "name": "Special Curry", "price": 4.00},
        {"id": "164", "name": "King Prawn Curry", "price": 4.50},
        {"id": "165", "name": "Chicken Curry", "price": 3.60},
        {"id": "166", "name": "Beef Curry", "price": 3.60},
        {"id": "167", "name": "Roast Pork Curry", "price": 3.60},
        {"id": "168", "name": "Shrimp Curry", "price": 3.60},
        {"id": "169", "name": "Roast Duck Curry", "price": 4.60},
        {"id": "16a", "name": "Hoi Sin Sauce", "price": 1.40},
        {"id": "170", "name": "Mushroom Curry", "price": 3.30},
    ],
    "chop suey": [
        {"id": "179", "name": "Special Chop Suey", "price": 3.70},
        {"id": "180", "name": "Chicken Chop Suey", "price": 3.50},
        {"id": "181", "name": "King Prawn Chop Suey", "price": 4.50},
        {"id": "182", "name": "Shrimp Chop Suey", "price": 3.60},
        {"id": "183", "name": "Beef Chop Suey", "price": 3.60},
        {"id": "184", "name": "Roast Pork Chop Suey", "price": 3.60},
        {"id": "185", "name": "Mushroom Chop Suey", "price": 3.40},
        {"id": "186", "name": "Vegetable Chop Suey", "price": 3.40},
        {"id": "187", "name": "Plain Chop Suey", "price": 3.00},
    ],
    "omelette": [
        {"id": "188", "name": "House Special Chop Suey", "price": 3.90},
        {"id": "189", "name": "Special Omelette", "price": 3.90},
        {"id": "190", "name": "Chicken Omelette", "price": 3.70},
        {"id": "191", "name": "King Prawn Omelette", "price": 4.40},
        {"id": "192", "name": "Shrimp Omelette", "price": 3.70},
        {"id": "193", "name": "Beef Omelette", "price": 3.70},
        {"id": "194", "name": "Roast Pork Omelette", "price": 3.70},
        {"id": "195", "name": "Mushroom Omelette", "price": 3.40},
        {"id": "196", "name": "Plain Omelette", "price": 3.20},
    ],
    "thaiDish": [
        {"id": "T1", "name": "Thoh Yun Goong", "price": 3.00},
        {"id": "T10", "name": "Garlic Chilli Prawns Thai Style", "price": 5.00},
        {"id": "T11", "name": "Red Curry with Chicken", "price": 4.40},
        {"id": "T12", "name": "Red Curry with Beef", "price": 4.70},
        {"id": "T13", "name": "Red Curry with Prawns", "price": 4.90},
        {"id": "T2", "name": "Thai King Prawn Fried Rice", "price": 4.70},
        {"id": "T3", "name": "Thai Chicken Fried Rice", "price": 4.60},
        {"id": "T4", "name": "Thai Chicken Chow Mein", "price": 4.60},
        {"id": "T5", "name": "Chilli Chicken Chow Mein", "price": 4.60},
        {"id": "T6", "name": "Chilli Beef Thai Style", "price": 4.60},
        {"id": "T7", "name": "Chill Prawns Thai Style", "price": 5.00},
        {"id": "T8", "name": "Garlic Chilli Chicken Thai Style ", "price": 4.40},
        {"id": "T9", "name": "Garlic Chilli Beef Thai Style", "price": 4.40},
    ],
}

export default menu;